import "@/styles/globals.css";

import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { WebsocketProvider } from "./_components/websocket-provider";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <WebsocketProvider>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </WebsocketProvider>
      </body>
    </html>
  );
}
